namespace Bloom.Common
{
	[default_interface]
	runtimeclass JDRGlobalXaml : Microsoft.UI.Xaml.Data.INotifyPropertyChanged
	{
		static JDRGlobalXaml getInstance();

	    // 暴露给XAML的runtimeclass属性 >>>>>>>>>>>>>>>>>>>>>>>>>>>
		Int32 Cnt{ get; set; };  // getter / setter 在XAML上可以显示/输入值

		// <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
	}
}
